spring.application.name=chat-system

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe?oracle.jdbc.mapDateToTimestamp=false

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.admin.username=${DEFAULT_ADMIN_USER}
app.admin.password=${DEFAULT_ADMIN_PASS}

app.jwt.secret=${JWT_SECRET}

#spring.datasource.username=chat_app
#spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update


